---
title: "Yinman Zhong GitHub Page"
description: "Describes the research, publications, and projects completed by Yinman Zhong."
keywords: "GitHub, research, public administration, public health, Yinman, Zhong, Yinman Zhong"
---
