name: Update Publications

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install scholarly

    - name: Run update script
      run: python update_publications.py

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token stored in GitHub Secrets
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git diff --cached --quiet || git commit -m 'Update recent publications' # Only commit if there are changes
        git push https://github.com/YinmanZhong/YinmanZhong.github.io.git HEAD:main
